### ISSUE TITLE
minecraft(SLPP) crashed TAT

### ISSUE THREAD

**Issue by bdralien** [frank89722/SmileLawmPreviewPack#1]
I couldn't open my game.
It crashed right after it finished loading the mods
if it's only because i'm out of RAM, could you please tell me what's the minimum RAM requirements ?
MY game version is SLPP 4.1
Thanks

crash report  :   http://pastebin.com/CEYEmrMG

**Comment by frank89722** [comment]
It need 6G ram to open.
Or you can try slpp lite, it only need 5g. :D
