### ISSUE TITLE
登入後退出+回朔

### ISSUE THREAD

**Issue by jw910731** [frank89722/SmileLawmPreviewPack#3]
我&朋友開的SV出了問題(是我開的)，我或我的朋友進去SV都會出現整個世界載入完畢且方塊互動正常(可以開箱子，穿越傳送門)的狀態下，在約15~30秒就退出。而且剛剛所做的移動、互動全部無效。
相關LOG:[http://pastebin.com/Vw47Qa3K](http://pastebin.com/Vw47Qa3K)

**Comment by frank89722** [comment]
https://github.com/TheDragonTeam/ArmorPlus/issues/69

**Comment by frank89722** [comment]
下次會報記得附上版本呦

**Comment by frank89722** [comment]
r5.0 已修復
