### ISSUE TITLE
終界水晶渲染會導致崩潰

### ISSUE THREAD

**Issue by jw910731** [frank89722/SmileLawmPreviewPack#7]
模組包版本:5.2
多人端使用:是
崩潰報告:[https://paste.ee/p/LN7Zv](https://paste.ee/p/LN7Zv)
敘述:在終界時在看到水晶的前一刻畫面頓住，然後崩饋
關鍵行數:27行，64~66行
暫時解決辦法:看到終界水晶前打/kill @e[type=EnderCrystal]把終界水晶殺死
P.S. 希望可以盡速修正，順便將本篇作為大家開Issue時的範本

**Comment by frank89722** [comment]
我沒昨天剛打完龍，沒有遇到這問題耶OAO

**Comment by frank89722** [comment]
你有帶拔刀劍在身上嗎?

**Comment by frank89722** [comment]
我看你記憶體只給4g，你要試著開到5g看看嗎?

**Comment by jw910731** [comment]
給Java 1024Mb~8192Mb PermGen給512Mb

**Comment by frank89722** [comment]
java8不能設定PermGen
java請把min和max同樣設定在6g試試看

這看起來是原版掛，並不是模組

**Comment by frank89722** [comment]
補充一下multimc PermGen讓它保持在原本的128別去動他

**Comment by jw910731** [comment]
=,,=連我用啥開都知道
真可怕的人

**Comment by frank89722** [comment]
crashreport都有寫

**Comment by jw910731** [comment]
似乎好了沒問題，但不能裝Optifine不然照樣崩(我有裝，朋友沒裝)

**Comment by frank89722** [comment]
這看起來不是我的問題，你是在多人server
那server上其他人會crash嗎?

**Comment by jw910731** [comment]
也會，剛剛條了Min Max都6G解不加參數的狀況，仍然崩潰

**Comment by frank89722** [comment]
如果只在單人會出現一樣的問題嗎?

**Comment by jw910731** [comment]
還有我朋友的部分EnderCrystal已不會繼續造成崩潰
自己這裡還沒試

**Comment by jw910731** [comment]
@frank89722 還沒有試過單人

**Comment by frank89722** [comment]
能試試看嘛?

**Comment by jw910731** [comment]
請問有用語音軟體嗎?如:RC或Curse，在這裡講非常不方便

**Comment by frank89722** [comment]
沒有

**Comment by jw910731** [comment]
那Discord呢?

**Comment by frank89722** [comment]
這應該不是我的問題，我多人跟單人都沒遇到

還有bug回報就這個管道跟巴哈，我沒有打算讓他人知道我的其他聯絡方式

**Comment by jw910731** [comment]
對不起，我會再去找資料解決的

**Comment by frank89722** [comment]
https://github.com/frank89722/SmileLawmPreviewPack/issues/9
