### ISSUE TITLE
龍之吐息導致單人端崩潰

### ISSUE THREAD

**Issue by jw910731** [frank89722/SmileLawmPreviewPack#8]
模組包版本:5.2
使用多人端:是
崩潰報告(SP):[https://paste.ee/p/VUYgv](https://paste.ee/p/VUYgv)
敘述:終界龍噴龍息時導致崩潰
關鍵行數:27行 60~62行  68行
暫時解決辦法:打龍時和龍保持距離，在龍回巢(飛到傳送門上)時不要靠近他(不然龍噴龍息=>Crash)
P.S.各種東西做不了拉T_T

**Comment by frank89722** [comment]
#7

**Comment by frank89722** [comment]
我沒發生這些問題，上一篇可以給個回應嗎?
別那麼急著開issue

**Comment by jw910731** [comment]
你是單人端打龍嗎?

**Comment by frank89722** [comment]
多人server

**Comment by frank89722** [comment]
合併至 #7
