### ISSUE TITLE
終結水晶 和 拔刀劍 導致crash

### ISSUE THREAD

**Issue by Suripe** [frank89722/SmileLawmPreviewPack#9]
版本5.2 多人

這個是終結水晶：http://pastebin.com/uURzT8Us
在進入終結時幾秒就crash了

這個是拔刀劍：http://pastebin.com/rgbPGxUM
把拔刀劍扔地上后就crash 我和我朋友都在伺服器上都遇到了

**Comment by Suripe** [comment]
單人測試就沒事

**Comment by frank89722** [comment]
哪個東西單人測沒問題?

**Comment by Suripe** [comment]
2個都沒事

**Comment by Suripe** [comment]
2個問題在單人都沒問題

**Comment by frank89722** [comment]
好，目前初估所有render問題都由拔刀劍造成
如果可以能否試試看多人和單人端都移除拔刀劍，然後再進去終界看看呢?

**Comment by Suripe** [comment]
刪除后沒問題

**Comment by frank89722** [comment]
等待Botania修一些bug之後會更新修復
在我把更新上傳到Curse這個issue才會close避免重複回報

**Comment by frank89722** [comment]
Fixed in 5.3
